name: Trigger Review Job on Comment

on:
  issue_comment:
    types: [created]

jobs:
  ReviewJob:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'review-pr')

    steps:
      - name: Run your review tasks
        env: 
          SUGGESTION_ENDPOINT: ${{ secrets.SUGGESTION_ENDPOINT }}
        run: |
          echo "PR Number: ${{ github.event.issue.number }}"
          ./scripts/call_suggestions.sh # Execute the script
          echo "Review completed!"
          # Replace this with your review process commands
