name: Trigger Review Job on Comment

on:
  issue_comment:
    types: [created]

jobs:
  Review:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'review-pr')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run your review tasks
        run: |
          # Replace this with your review process commands, e.g.,
          # npm install
          # npm test
          # echo "Review completed!"
