name: Trigger Review Job on Comment

on:
  issue_comment:
    types: [created]

jobs:
  ReviewJob:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'review-pr')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run your review tasks
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          SUGGESTION_ENDPOINT: ${{ vars.SUGGESTION_ENDPOINT }}
          KEYWORDS: ${{ vars.KEYWORDS }}
        run: |
          echo "Create review for PR Number: $PR_NUMBER"
          ./scripts/call_suggestions.sh # Execute the script
          echo "Review completed!"
          # Replace this with your review process commands
